project:
  type: website
  output-dir: "."
  
website:
  title: "Home<br><small>홈</small>"
  # favicon: images/wedding_title.svg
  search: false
  description: "Wedding Photo Gallery"
  # page-footer: "Copyright 2025 © Byeong-Hak Choe & Alivia Cochran"
  navbar:
    pinned: true
    # logo: images/wedding_title3.png  # Path to your logo file
    left:
      - text: "Highlights<br><small>주요장면</small>"
        href: Highlights/index_highlights.html
      - text: "Friends & Family<br><small>친구가족</small>"
        href: Friends & Family/index_ff.html
      - text: "Pre-Ceremony<br><small>예식전</small>"
        href: Pre-Ceremony/index_pre.html
      - text: "Ceremony<br><small>결혼식</small>"
        href: Ceremony/index_ceremony.html
      - text: "Reception<br><small>연회</small>"
        href: Reception/index_reception.html
      - text: "Before & After<br><small>결혼전후</small>"
        href: Pre-Post-Wedding/index_prepost.html

format:
  html:
    theme:
      light: litera
    css: styles.css
    fontsize: 1.4rem
    linestretch: 1.4
    toc: true
    
execute:
  freeze: false