project:
  type: website
  output-dir: "."
  
website:
  title: ""
  # favicon: images/wedding_title.svg
  search: false
  description: "Wedding Photo Gallery"
  # page-footer: "Copyright 2025 © Byeong-Hak Choe & Alivia Cochran"
  navbar:
    pinned: true
    logo: images/wedding_title3.png  # Path to your logo file
    left:
      - text: "Highlights 주요장면"
        href: Highlights/index_highlights.html
      - text: "Friends & Family 친구가족"
        href: Friends & Family/index_ff.html
      - text: "Pre-Ceremony 예식전"
        href: Pre-Ceremony/index_pre.html
      - text: "Ceremony 결혼식"
        href: Ceremony/index_ceremony.html
      - text: "Reception 연회"
        href: Reception/index_reception.html
      - text: "Pre-Wedding 결혼전"
        href: /index_prew.html

format:
  html:
    theme:
      light: litera
    css: styles.css
    fontsize: 1.4rem
    linestretch: 1.4
    toc: true
    
execute:
  freeze: false